### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by klasrocket** [vranki/siilihai-client#3]
Hi.

I just found Siilihai again and really looking forward to be able to use it but now I get stuck at connecting to the server, I guess it might be  the same issue as mentioned in the blog; www.siilihai.com/news.html
a while ago though.

![screenshot from 2017-07-29 22-55-47](https://user-images.githubusercontent.com/455912/28748213-020d5c8e-74b2-11e7-8759-31f7e2ddd1da.png)

**Comment by klasrocket** [comment]
Seems to be affecting a lot of functions even when using Siilihai without sync set up.

**Comment by klasrocket** [comment]
Even when setting up a new parser it seems to be no way of saving it locally, is there any documentation of the server side, I thought it might be neat to set up an own server or run it with nextcloud maybe.

**Comment by vranki** [comment]
The server is still broken. I've upgraded the code to latest Django, but authentication fails for some reason. 

I'm planning to release the server as open source when it's back working and cleaned up. Sorry, this has taken for too long (summer vacations & all).

**Comment by klasrocket** [comment]
Ok, sorry to hear. Seems to be you doing all the work so I totally understand that some issues takes time. I'm definitely not experienced in python or django, but if you want some help I might be to some good.

**Comment by klasrocket** [comment]
as I mentioned I'm quite new to django but started trying to put something together that can respond to siilihai. even if you cannot share the whole sever code, would you mind share some hints, info or XML examples? I saw that you made commits to mezzanine but that's not used for the siilihai server right?

**Comment by vranki** [comment]
There was some progress this weekend, now i know how to setup the server from blank state (could do a Docker container of it maybe..) but the auth issue remains. I hope i can solve it this week. It's probably just one time issue, auth middleware not being able to read the old version database. I don't know yet why it can't migrate it to newer scheme automatically.

**Comment by vranki** [comment]
Good news! I have the authentication issue solved. Now the work is going to fix all remaining things that broke during Django & Python upgrade. Surprisingly lot of work but it's progressing fast now.

**Comment by klasrocket** [comment]
awsome! glad to hear that, looking forward to be able to use it and hopefully contribute as well.

**Comment by vranki** [comment]
The server is now updated to a working version. I had to modify the protocol also a little so a client update is required.
Client in git should now more or less work. Everything hasn't been tested properly but at least i can log in, sync, subscribe to forums and quit cleanly.

**Comment by klasrocket** [comment]
nice! seems to be functioning for me as well!
