### ISSUE TITLE
Unable to save new parser

### ISSUE THREAD

**Issue by klasrocket** [vranki/siilihai-client#5]
I still can't save a new parser, after commit [8fa39ba35e69b56ad6043bceeae3e22ff7aac359](https://github.com/vranki/libsiilihai/commit/8fa39ba35e69b56ad6043bceeae3e22ff7aac359)
I don't know if it's client, lib or serverside issue, can I get some hints to debug?

**Comment by vranki** [comment]
What happens? Parser maker says it can't save parser? Are you logged in with the client? Maybe the console output shows something related. You might also look at the network traffic with Wireshark and see what is being sent and received. I looked at server logs and found only bug related to unsubscribing forums and i already fixed that on server.

**Comment by klasrocket** [comment]
Nothing useful in Application output in QT Creator as far as I can see. Provided a wireshark dump, wil try to evaluate it.

[siilihai.pcapng.tar.gz](https://github.com/vranki/siilihai-client/files/1275427/siilihai.pcapng.tar.gz)

Some screenshots if I missed something obviuos, the message pattern is not working properly, but I guess thats not the problem:

![screenshot from 2017-09-04 21-23-34](https://user-images.githubusercontent.com/455912/30037477-75920f30-91bb-11e7-95ca-4597ce018bac.png)

![screenshot from 2017-09-04 21-24-28](https://user-images.githubusercontent.com/455912/30037480-7a946c08-91bb-11e7-8f8e-d9972ee7c811.png)

![screenshot from 2017-09-04 21-24-47](https://user-images.githubusercontent.com/455912/30037483-8049931c-91bb-11e7-9a41-09ea38bdda73.png)

![screenshot from 2017-09-04 21-25-08](https://user-images.githubusercontent.com/455912/30037485-851a73ac-91bb-11e7-829c-542d6b94fe3c.png)

**Comment by klasrocket** [comment]
![screenshot from 2017-09-04 21-54-50](https://user-images.githubusercontent.com/455912/30037508-b346aafc-91bb-11e7-93bf-cf82098a8d84.png)

**Comment by klasrocket** [comment]
So I guess the server validating all the info in the save request and sends back an int that's represents if the save request was successful or not. so if the problem is not at server side the info in the save request is probably not correct?

**Comment by vranki** [comment]
Could you try again? I refactored the parser saving code and was able to create a new test parser. If you need to add some test parser, just add TEST in the name so I'll delete them later.

**Comment by klasrocket** [comment]
Yes! Now it seems to work fine, awsome, thanks! So you did the refactoring at server side?
Is the procedure to make a parser, that you save it, then wait for it to be confirmed and then you ad it to your forumlist from subscribe menu?

**Comment by klasrocket** [comment]
Yes! Now it seems to work fine, awsome, thanks! So you did the refactoring at server side?
